version: '3.9'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "keinos/sqlite3:latest"
    volumes:
      - "./data:/var/lib/sqlite"
